spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration

server:
  port: 8080

management:
  server:
    port: 8081
    base-path: /
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus,metrics

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

jdbc:
  username: user
  password: password
  initSql: 'SELECT 1'
  url: jdbc:postgresql://localhost:5432/database
  schema: database
  maxPoolSize: 5
  maxLifetimeInMinutes: 10
  leakDetectionThresholdInMilliseconds: 2000
  connectionTimeoutInMilliseconds: 1000